### ISSUE TITLE
mailto randomness

### ISSUE THREAD

**Issue by melisgl** [3b/3bmd#20]
When a mailto element is printed to html there is randomness injected into the encoding supposedly to make life more difficult for spammers:

```
(defun encode-email (text)
  (with-output-to-string (s)
    (loop for i across text
       for r = (random 1.0)
       do (cond
            ((< r 0.1) (write-char i s))
            ;; fixme: make this portable to non-unicode/ascii lisps?
            ((< r 0.6) (format s "&#x~x;" (char-code i)))
            (t (format s "&#~d;" (char-code i)))))))
```

Unfortunately, this has the side effect of introducing spurious diffs when the generated html is version controlled. Would a deterministic solution be acceptable?

**Comment by 3b** [comment]
fixed by #21, thanks for the patch
