### ISSUE TITLE
Code blocks highlighting

### ISSUE THREAD

**Issue by Ferada** [3b/3bmd#23]
It seems that regular, indented code blocks are treated differently than unindented (marked with ```) code blocks in terms of highlighting? IMO, even though there's currently no way to set a language, the indented code blocks should also undergo highlighting, at least that's how other formatters, e.g. Stackoverflow render it too.

**Comment by ljanyst** [comment]
Have a look at the `*render-code-spans-lang*` parameter.

**Comment by 3b** [comment]
`3bmd-ext-code-blocks` has support for highlighting code spans, with the previously mentioned `*render-code-spans-lang*`. Don't see it documented though, so will add that.
