### ISSUE TITLE
Pygments option to ext-code-blocks extension should probably be secured better

### ISSUE THREAD

**Issue by 3b** [3b/3bmd#29]
Currently the Pygments mode of `ext-code-blocks` passes user input to the `pygmentize` for the language and options. The code tries to do so safely by trying to avoid going through a shell and rejecting the `cssfile` option, but it would probably be better to whitelist the allowed options and either whitelist the languages (possibly querying from `pygmentize` on first use?) or at least restrict the characters allowed.

**Comment by 3b** [comment]
Probably also should add an option to disable passing options to pygments completely, not sure if they could be used to add bad things to the html output?

**Comment by 3b** [comment]
Yeah, looks like XSS is a problem with arbitrary options, so disabled by default until they can be whitelisted.

**Comment by 3b** [comment]
After further thought, XSS might not be as much of a concern considering you can embed arbitrary HTML in markdown already. Probably could be convinced to change defaults if anyone cares, though that adds HTML blocks to the list of things that one should be able to disable.

**Comment by 3b** [comment]
And after a bit of research, it seems trying to prevent XSS in markdown is pointless and there should be a separate process to clean up the HTML output. Reverting the change that disabled options.

**Comment by ljanyst** [comment]
I will re-write it completely. It's excruciatingly slow. My blog takes a second to render without code blocks enabled and over two minutes with them. The overhead comes from spawning new python processes each time a block is processed.
