### ISSUE TITLE
Accepting empty cells in table

### ISSUE THREAD

**Issue by ta2gch** [3b/3bmd#34]
3bmd-ext-tables ignore empty cells in table. In a following text,  3bmd don't render correctly.

```
| a |   |
| - | - |
|   | b |
```

I expect to render like a following.

| a |   |
| - | - |
|   | b |

I guess the cause is https://github.com/3b/3bmd/blob/5b301ade30d5cbaf76c5b53d35d2482850cdeb1b/tables.lisp#L37

Thank you.

**Comment by 3b** [comment]
Should be fixed, thanks.
