### ISSUE TITLE
# interpreted as title inside of lists

### ISSUE THREAD

**Issue by alarsyo** [3b/3bmd#35]
Something like `* #not a  title` will be rendered as

```html
<ul>
<li><h1>not a title</h1></li>
</ul>
```

when it should just be

```html
<ul>
<li>#not a title</li>
</ul>
```

**Comment by 3b** [comment]
Hmm, original markdown doesn't parse `#` headings in lists, while commonmark does. Commonmark says `#x` isn't a heading though, and you need a space like `# x`. So 3bmd doesn't agree with either for that specific example. I'd probably lean towards fixing it to match commonmark if anything. 

Actually, looking closer, original markdown does parse them *sometimes*, so I think I will close this as `won't fix` and add tests to indicate the mismatch with commonmark about requiring a space so it can be fixed at some point.

Assuming you still care about 3bmd (sorry about the very slow response), feel free to reopen with comments if you disagree, or to open a new bug if requiring the space after `#`  would also fix your problem and you would like to see that sooner.

tested on https://daringfireball.net/projects/markdown/dingus (with spaces after # for comparison with gfm, but didn't change the parse as far as I could see)

```markdown
* # not a title
* # title?

  # title?
* # not a title
  # not a title
```
->
```html
<ul>
<li># not a title</li>
<li><h1>title?</h1>

<h1>title?</h1></li>
<li># not a title
# not a title</li>
</ul>
```
and
```markdown
* # title

* ## title

* ### title
```
->
```html
<ul>
<li><h1>title</h1></li>
<li><h2>title</h2></li>
<li><h3>title</h3></li>
</ul>
```

and directly in gfm (based on commonmark)

* # not a title
* # title?

  # title?
* # not a title
  # not a title

and


* # title

* ## title

* ### title

but `#x` without the space isn't a title in gfm/commonmark:
# title (`# title`)
#not a title (`#not a title`)

**Comment by alarsyo** [comment]
> Assuming you still care about 3bmd (sorry about the very slow response)

Ha, I can't remember when I encountered this problem :sweat_smile: . No worries about the response delay, sometimes life gets in the way :) 

Interesting behavior from CommonMark, I agree with your reasoning!
