### ISSUE TITLE
Escaping curly brackets

### ISSUE THREAD

**Issue by melisgl** [3b/3bmd#59]
In commit 18a59d3, I changed `print-md-escaped` to escape the `[]` and `{}` characters. The former was necessary for print/parse consistency, while the latter wasn't because `{}` are not parsed specially (except for allowing them to be backslash escaped). However, in https://github.com/melisgl/mgl-pax/pull/28, we find that escaping curly brackets makes outputting latex-in-markdown for pandoc a pain.

Do you think not escaping them would be correct?

**Comment by 3b** [comment]
fixed along with #60 i think
